/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon/battle`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon/exploration`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon`; params?: Router.UnknownInputParams; } | { pathname: `/party`; params?: Router.UnknownInputParams; } | { pathname: `/characters`; params?: Router.UnknownInputParams; } | { pathname: `/characters/new`; params?: Router.UnknownInputParams; } | { pathname: `/characters/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/characters/[id]/tactics`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/dungeon/battle`; params?: Router.UnknownOutputParams; } | { pathname: `/dungeon/exploration`; params?: Router.UnknownOutputParams; } | { pathname: `/dungeon`; params?: Router.UnknownOutputParams; } | { pathname: `/party`; params?: Router.UnknownOutputParams; } | { pathname: `/characters`; params?: Router.UnknownOutputParams; } | { pathname: `/characters/new`; params?: Router.UnknownOutputParams; } | { pathname: `/characters/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/characters/[id]/tactics`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/dungeon/battle${`?${string}` | `#${string}` | ''}` | `/dungeon/exploration${`?${string}` | `#${string}` | ''}` | `/dungeon${`?${string}` | `#${string}` | ''}` | `/party${`?${string}` | `#${string}` | ''}` | `/characters${`?${string}` | `#${string}` | ''}` | `/characters/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon/battle`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon/exploration`; params?: Router.UnknownInputParams; } | { pathname: `/dungeon`; params?: Router.UnknownInputParams; } | { pathname: `/party`; params?: Router.UnknownInputParams; } | { pathname: `/characters`; params?: Router.UnknownInputParams; } | { pathname: `/characters/new`; params?: Router.UnknownInputParams; } | `/characters/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/characters/${Router.SingleRoutePart<T>}/tactics${`?${string}` | `#${string}` | ''}` | { pathname: `/characters/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/characters/[id]/tactics`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
